export const GET_EVENT_BY_ID = 'GET_EVENT_BY_ID';
export const FIND_EVENTS = 'FIND_EVENTS';
export const APPROVE_EVENT = 'APPROVE_EVENT';
export const REFUSE_EVENT = 'REFUSE_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const DELETE_EVENTS = 'DELETE_EVENTS';
export const CLEAR_EVENT_DATA = 'CLEAR_EVENT_DATA';
